<<measureg1,include=FALSE>>=
  #source( 
  #  'http://www.statpower.net/Content/312/R Stuff/AdvancedFactorFunctionsV1.04.r') 
  library(psych)
library(ltm)
library(irtoys)
library(GPArotation)

##Data Management
fullasvab <- read.csv("E:\\Dropbox\\Work\\Research\\Projects\\NLSY\\Not Current\\79\\ASVAB\\asvab.csv",header=TRUE)

cleanavsab<-fullasvab
cleanavsab[cleanavsab==-4] <- NA
cleanavsab$SAMPLE_RACE <- factor(cleanavsab$SAMPLE_RACE)
cleanavsab$SAMPLE_SEX <- factor(cleanavsab$SAMPLE_SEX)
asvab<-cleanavsab

remove(cleanavsab)
remove(fullasvab)
attach(asvab)
AR<-data.frame(ASVAB.ARITHMETIC.REASONING.1,ASVAB.ARITHMETIC.REASONING.2,ASVAB.ARITHMETIC.REASONING.3,ASVAB.ARITHMETIC.REASONING.4,ASVAB.ARITHMETIC.REASONING.5,ASVAB.ARITHMETIC.REASONING.6,ASVAB.ARITHMETIC.REASONING.7,ASVAB.ARITHMETIC.REASONING.8,ASVAB.ARITHMETIC.REASONING.9,ASVAB.ARITHMETIC.REASONING.10,ASVAB.ARITHMETIC.REASONING.11,ASVAB.ARITHMETIC.REASONING.12,ASVAB.ARITHMETIC.REASONING.13,ASVAB.ARITHMETIC.REASONING.14,ASVAB.ARITHMETIC.REASONING.15,ASVAB.ARITHMETIC.REASONING.16,ASVAB.ARITHMETIC.REASONING.17,ASVAB.ARITHMETIC.REASONING.18,ASVAB.ARITHMETIC.REASONING.19,ASVAB.ARITHMETIC.REASONING.20,ASVAB.ARITHMETIC.REASONING.21,ASVAB.ARITHMETIC.REASONING.22,ASVAB.ARITHMETIC.REASONING.23,ASVAB.ARITHMETIC.REASONING.24,ASVAB.ARITHMETIC.REASONING.25,ASVAB.ARITHMETIC.REASONING.26,ASVAB.ARITHMETIC.REASONING.27,ASVAB.ARITHMETIC.REASONING.28,ASVAB.ARITHMETIC.REASONING.29,ASVAB.ARITHMETIC.REASONING.30)
names(AR) <- paste0("AR", seq_along(AR))
MK<-data.frame(ASVAB.MATHEMATICS.KNOWLEDGE.1,ASVAB.MATHEMATICS.KNOWLEDGE.2,ASVAB.MATHEMATICS.KNOWLEDGE.3,ASVAB.MATHEMATICS.KNOWLEDGE.4,ASVAB.MATHEMATICS.KNOWLEDGE.5,ASVAB.MATHEMATICS.KNOWLEDGE.6,ASVAB.MATHEMATICS.KNOWLEDGE.7,ASVAB.MATHEMATICS.KNOWLEDGE.8,ASVAB.MATHEMATICS.KNOWLEDGE.9,ASVAB.MATHEMATICS.KNOWLEDGE.10,ASVAB.MATHEMATICS.KNOWLEDGE.11,ASVAB.MATHEMATICS.KNOWLEDGE.12,ASVAB.MATHEMATICS.KNOWLEDGE.13,ASVAB.MATHEMATICS.KNOWLEDGE.14,ASVAB.MATHEMATICS.KNOWLEDGE.15,ASVAB.MATHEMATICS.KNOWLEDGE.16,ASVAB.MATHEMATICS.KNOWLEDGE.17,ASVAB.MATHEMATICS.KNOWLEDGE.18,ASVAB.MATHEMATICS.KNOWLEDGE.19,ASVAB.MATHEMATICS.KNOWLEDGE.20,ASVAB.MATHEMATICS.KNOWLEDGE.21,ASVAB.MATHEMATICS.KNOWLEDGE.22,ASVAB.MATHEMATICS.KNOWLEDGE.23,ASVAB.MATHEMATICS.KNOWLEDGE.24,ASVAB.MATHEMATICS.KNOWLEDGE.25)
names(MK) <- paste0("MK", seq_along(MK))
WK<-data.frame(ASVAB.WORD.KNOWLEDGE.1,ASVAB.WORD.KNOWLEDGE.2,ASVAB.WORD.KNOWLEDGE.3,ASVAB.WORD.KNOWLEDGE.4,ASVAB.WORD.KNOWLEDGE.5,ASVAB.WORD.KNOWLEDGE.6,ASVAB.WORD.KNOWLEDGE.7,ASVAB.WORD.KNOWLEDGE.8,ASVAB.WORD.KNOWLEDGE.9,ASVAB.WORD.KNOWLEDGE.10,ASVAB.WORD.KNOWLEDGE.11,ASVAB.WORD.KNOWLEDGE.12,ASVAB.WORD.KNOWLEDGE.13,ASVAB.WORD.KNOWLEDGE.14,ASVAB.WORD.KNOWLEDGE.15,ASVAB.WORD.KNOWLEDGE.16,ASVAB.WORD.KNOWLEDGE.17,ASVAB.WORD.KNOWLEDGE.18,ASVAB.WORD.KNOWLEDGE.19,ASVAB.WORD.KNOWLEDGE.20,ASVAB.WORD.KNOWLEDGE.21,ASVAB.WORD.KNOWLEDGE.22,ASVAB.WORD.KNOWLEDGE.23,ASVAB.WORD.KNOWLEDGE.24,ASVAB.WORD.KNOWLEDGE.25,ASVAB.WORD.KNOWLEDGE.26,ASVAB.WORD.KNOWLEDGE.27,ASVAB.WORD.KNOWLEDGE.28,ASVAB.WORD.KNOWLEDGE.29,ASVAB.WORD.KNOWLEDGE.30,ASVAB.WORD.KNOWLEDGE.31,ASVAB.WORD.KNOWLEDGE.32,ASVAB.WORD.KNOWLEDGE.33,ASVAB.WORD.KNOWLEDGE.34,ASVAB.WORD.KNOWLEDGE.35)
names(WK) <- paste0("WK", seq_along(WK))
PC<-data.frame(ASVAB.PARAGRAPH.COMPREHENSION.1,ASVAB.PARAGRAPH.COMPREHENSION.2,ASVAB.PARAGRAPH.COMPREHENSION.3,ASVAB.PARAGRAPH.COMPREHENSION.4,ASVAB.PARAGRAPH.COMPREHENSION.5,ASVAB.PARAGRAPH.COMPREHENSION.6,ASVAB.PARAGRAPH.COMPREHENSION.7,ASVAB.PARAGRAPH.COMPREHENSION.8,ASVAB.PARAGRAPH.COMPREHENSION.9,ASVAB.PARAGRAPH.COMPREHENSION.10,ASVAB.PARAGRAPH.COMPREHENSION.11,ASVAB.PARAGRAPH.COMPREHENSION.12,ASVAB.PARAGRAPH.COMPREHENSION.13,ASVAB.PARAGRAPH.COMPREHENSION.14,ASVAB.PARAGRAPH.COMPREHENSION.15)
names(PC) <- paste0("PC", seq_along(PC))
AFQT<-data.frame(AR,MK,WK,PC)
AFQT_Quant<-data.frame(AR,MK)
AFQT_Verbal<-data.frame(WK,PC)

AFQT_nopc15<-AFQT
AFQT_nopc15$PC15<-NULL
detach(asvab)
data <- AFQT
S<-hetcor(data)
#R <- cor(data, use="complete.obs")
R<-S$correlations
n <- dim(data)[1]

#png(filename=paste(file_drive,"/Dropbox/Work/Research/Projects/NLSY/AFI/R/plots/screegen1.png",sep=""), width = 505, height = 500)
#Scree.Plot(R,main="Data")
#grid.arrange(Sibintel, Sibcs, ncol=2,heights=1, widths=c(1,.875))
#dev.off()
#png(filename=paste(file_drive,"/Dropbox/Work/Research/Projects/NLSY/AFI/R/plots/RMSEAgen1.png",sep=""), width = 505, height = 500)
#FA.Stats(R,n.factors=1:5,n.obs=n, main="RMSEA Plot",
#         RMSEA.cutoff=0.05)
#dev.off()
@